spring:
  application:
    name: heycar
  servlet:
    multipart:
      max-file-size: 12MB
      max-request-size: 12MB
      enabled: true
server:
  port: ${DISCOVERED_SERVICE_PORT:8082}
logging:
  level:
    root: INFO
app:
  api:
    endpoint:
      listing:
        retrieve:
          byCodeAndDealer: /v1/listing/{code}/{dealerId}
        upload:
          csv: /v1/upload_csv
          json: /v1/upload_json
        search:
          retrieve_by_dealer: /v1/listing/dealer/{id}
          retrieve_by_dealer_and_code: /v1/listing/dealer/{id_dealer}/code/{id_code}
storage:
  location: ./uploads